using Microsoft.EntityFrameworkCore.Migrations;

namespace E2E_SkillEvaluationTest.Migrations
{
    public partial class init : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Todos",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Title = table.Column<string>(nullable: true),
                    Completed = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Todos", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Todos",
                columns: new[] { "Id", "Completed", "Title" },
                values: new object[,]
                {
                    { 1, false, "delectus aut autem" },
                    { 128, false, "eius omnis est qui voluptatem autem" },
                    { 129, false, "rerum culpa quis harum" },
                    { 130, true, "nulla aliquid eveniet harum laborum libero alias ut unde" },
                    { 131, false, "qui ea incidunt quis" },
                    { 132, true, "qui molestiae voluptatibus velit iure harum quisquam" },
                    { 133, true, "et labore eos enim rerum consequatur sunt" },
                    { 134, false, "molestiae doloribus et laborum quod ea" },
                    { 135, false, "facere ipsa nam eum voluptates reiciendis vero qui" },
                    { 136, false, "asperiores illo tempora fuga sed ut quasi adipisci" },
                    { 137, false, "qui sit non" },
                    { 138, true, "placeat minima consequatur rem qui ut" },
                    { 139, false, "consequatur doloribus id possimus voluptas a voluptatem" },
                    { 140, true, "aut consectetur in blanditiis deserunt quia sed laboriosam" },
                    { 141, true, "explicabo consectetur debitis voluptates quas quae culpa rerum non" },
                    { 142, true, "maiores accusantium architecto necessitatibus reiciendis ea aut" },
                    { 143, false, "eum non recusandae cupiditate animi" },
                    { 144, false, "ut eum exercitationem sint" },
                    { 145, false, "beatae qui ullam incidunt voluptatem non nisi aliquam" },
                    { 146, true, "molestiae suscipit ratione nihil odio libero impedit vero totam" },
                    { 147, true, "eum itaque quod reprehenderit et facilis dolor autem ut" },
                    { 148, false, "esse quas et quo quasi exercitationem" },
                    { 127, true, "voluptatem libero consectetur rerum ut" },
                    { 149, false, "animi voluptas quod perferendis est" },
                    { 126, true, "ut asperiores perspiciatis veniam ipsum rerum saepe" },
                    { 124, false, "qui consectetur id" },
                    { 103, false, "non sunt delectus illo nulla tenetur enim omnis" },
                    { 104, false, "excepturi non laudantium quo" },
                    { 105, true, "totam quia dolorem et illum repellat voluptas optio" },
                    { 106, true, "ad illo quis voluptatem temporibus" },
                    { 107, false, "praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt" },
                    { 108, true, "a eos eaque nihil et exercitationem incidunt delectus" },
                    { 109, true, "autem temporibus harum quisquam in culpa" },
                    { 110, true, "aut aut ea corporis" },
                    { 111, false, "magni accusantium labore et id quis provident" },
                    { 112, false, "consectetur impedit quisquam qui deserunt non rerum consequuntur eius" },
                    { 113, false, "quia atque aliquam sunt impedit voluptatum rerum assumenda nisi" },
                    { 114, false, "cupiditate quos possimus corporis quisquam exercitationem beatae" },
                    { 115, false, "sed et ea eum" },
                    { 116, true, "ipsa dolores vel facilis ut" },
                    { 117, false, "sequi quae est et qui qui eveniet asperiores" },
                    { 118, false, "quia modi consequatur vero fugiat" },
                    { 119, false, "corporis ducimus ea perspiciatis iste" },
                    { 120, false, "dolorem laboriosam vel voluptas et aliquam quasi" },
                    { 121, true, "inventore aut nihil minima laudantium hic qui omnis" },
                    { 122, true, "provident aut nobis culpa" },
                    { 123, false, "esse et quis iste est earum aut impedit" },
                    { 125, false, "aut quasi autem iste tempore illum possimus" },
                    { 102, false, "sed ab consequatur" },
                    { 150, false, "eos amet tempore laudantium fugit a" },
                    { 152, false, "odit eligendi recusandae doloremque cumque non" },
                    { 178, true, "nesciunt itaque commodi tempore" },
                    { 179, true, "omnis consequuntur cupiditate impedit itaque ipsam quo" },
                    { 180, true, "debitis nisi et dolorem repellat et" },
                    { 181, false, "ut cupiditate sequi aliquam fuga maiores" },
                    { 182, true, "inventore saepe cumque et aut illum enim" },
                    { 183, true, "omnis nulla eum aliquam distinctio" },
                    { 184, false, "molestias modi perferendis perspiciatis" },
                    { 185, false, "voluptates dignissimos sed doloribus animi quaerat aut" },
                    { 186, false, "explicabo odio est et" },
                    { 187, false, "consequuntur animi possimus" },
                    { 188, true, "vel non beatae est" },
                    { 189, true, "culpa eius et voluptatem et" },
                    { 190, true, "accusamus sint iusto et voluptatem exercitationem" },
                    { 191, true, "temporibus atque distinctio omnis eius impedit tempore molestias pariatur" },
                    { 192, false, "ut quas possimus exercitationem sint voluptates" },
                    { 193, true, "rerum debitis voluptatem qui eveniet tempora distinctio a" },
                    { 194, false, "sed ut vero sit molestiae" },
                    { 195, true, "rerum ex veniam mollitia voluptatibus pariatur" },
                    { 196, true, "consequuntur aut ut fugit similique" },
                    { 197, true, "dignissimos quo nobis earum saepe" },
                    { 198, true, "quis eius est sint explicabo" },
                    { 177, false, "et placeat temporibus voluptas est tempora quos quibusdam" },
                    { 151, true, "accusamus adipisci dicta qui quo ea explicabo sed vero" },
                    { 176, false, "magni soluta corrupti ut maiores rem quidem" },
                    { 174, false, "similique aut quo" },
                    { 153, false, "ea aperiam consequatur qui repellat eos" },
                    { 154, true, "rerum non ex sapiente" },
                    { 155, true, "voluptatem nobis consequatur et assumenda magnam" },
                    { 156, true, "nam quia quia nulla repellat assumenda quibusdam sit nobis" },
                    { 157, true, "dolorem veniam quisquam deserunt repellendus" },
                    { 158, true, "debitis vitae delectus et harum accusamus aut deleniti a" },
                    { 159, true, "debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis" },
                    { 160, false, "et praesentium aliquam est" },
                    { 161, true, "ex hic consequuntur earum omnis alias ut occaecati culpa" },
                    { 162, true, "omnis laboriosam molestias animi sunt dolore" },
                    { 163, false, "natus corrupti maxime laudantium et voluptatem laboriosam odit" },
                    { 164, false, "reprehenderit quos aut aut consequatur est sed" },
                    { 165, false, "fugiat perferendis sed aut quidem" },
                    { 166, false, "quos quo possimus suscipit minima ut" },
                    { 167, false, "et quis minus quo a asperiores molestiae" },
                    { 168, false, "recusandae quia qui sunt libero" },
                    { 169, true, "ea odio perferendis officiis" },
                    { 170, false, "quisquam aliquam quia doloribus aut" },
                    { 171, true, "fugiat aut voluptatibus corrupti deleniti velit iste odio" },
                    { 172, false, "et provident amet rerum consectetur et voluptatum" },
                    { 173, false, "harum ad aperiam quis" },
                    { 175, true, "laudantium eius officia perferendis provident perspiciatis asperiores" },
                    { 101, false, "explicabo enim cumque porro aperiam occaecati minima" },
                    { 100, false, "excepturi a et neque qui expedita vel voluptate" },
                    { 99, false, "neque voluptates ratione" },
                    { 27, true, "veritatis pariatur delectus" },
                    { 28, false, "nesciunt totam sit blanditiis sit" },
                    { 29, false, "laborum aut in quam" },
                    { 30, true, "nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis" },
                    { 31, false, "repudiandae totam in est sint facere fuga" },
                    { 32, false, "earum doloribus ea doloremque quis" },
                    { 33, false, "sint sit aut vero" },
                    { 34, false, "porro aut necessitatibus eaque distinctio" },
                    { 35, true, "repellendus veritatis molestias dicta incidunt" },
                    { 36, true, "excepturi deleniti adipisci voluptatem et neque optio illum ad" },
                    { 37, false, "sunt cum tempora" },
                    { 38, false, "totam quia non" },
                    { 39, false, "doloremque quibusdam asperiores libero corrupti illum qui omnis" },
                    { 40, true, "totam atque quo nesciunt" },
                    { 41, false, "aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit" },
                    { 42, false, "rerum perferendis error quia ut eveniet" },
                    { 43, true, "tempore ut sint quis recusandae" },
                    { 44, true, "cum debitis quis accusamus doloremque ipsa natus sapiente omnis" },
                    { 45, false, "velit soluta adipisci molestias reiciendis harum" },
                    { 46, false, "vel voluptatem repellat nihil placeat corporis" },
                    { 47, false, "nam qui rerum fugiat accusamus" },
                    { 26, true, "aliquam aut quasi" },
                    { 48, false, "sit reprehenderit omnis quia" },
                    { 25, true, "voluptas quo tenetur perspiciatis explicabo natus" },
                    { 23, false, "et itaque necessitatibus maxime molestiae qui quas velit" },
                    { 2, false, "quis ut nam facilis et officia qui" },
                    { 3, false, "fugiat veniam minus" },
                    { 4, true, "et porro tempora" },
                    { 5, false, "laboriosam mollitia et enim quasi adipisci quia provident illum" },
                    { 6, false, "qui ullam ratione quibusdam voluptatem quia omnis" },
                    { 7, false, "illo expedita consequatur quia in" },
                    { 8, true, "quo adipisci enim quam ut ab" },
                    { 9, false, "molestiae perspiciatis ipsa" },
                    { 10, true, "illo est ratione doloremque quia maiores aut" },
                    { 11, true, "vero rerum temporibus dolor" },
                    { 12, true, "ipsa repellendus fugit nisi" },
                    { 13, false, "et doloremque nulla" },
                    { 14, true, "repellendus sunt dolores architecto voluptatum" },
                    { 15, true, "ab voluptatum amet voluptas" },
                    { 16, true, "accusamus eos facilis sint et aut voluptatem" },
                    { 17, true, "quo laboriosam deleniti aut qui" },
                    { 18, false, "dolorum est consequatur ea mollitia in culpa" },
                    { 19, true, "molestiae ipsa aut voluptatibus pariatur dolor nihil" },
                    { 20, true, "ullam nobis libero sapiente ad optio sint" },
                    { 21, false, "suscipit repellat esse quibusdam voluptatem incidunt" },
                    { 22, true, "distinctio vitae autem nihil ut molestias quo" },
                    { 24, false, "adipisci non ad dicta qui amet quaerat doloribus ea" },
                    { 49, false, "ut necessitatibus aut maiores debitis officia blanditiis velit et" },
                    { 50, true, "cupiditate necessitatibus ullam aut quis dolor voluptate" },
                    { 51, false, "distinctio exercitationem ab doloribus" },
                    { 78, false, "reiciendis est magnam amet nemo iste recusandae impedit quaerat" },
                    { 79, true, "eum ipsa maxime ut" },
                    { 80, true, "tempore molestias dolores rerum sequi voluptates ipsum consequatur" },
                    { 81, true, "suscipit qui totam" },
                    { 82, false, "voluptates eum voluptas et dicta" },
                    { 83, true, "quidem at rerum quis ex aut sit quam" },
                    { 84, false, "sunt veritatis ut voluptate" },
                    { 85, true, "et quia ad iste a" },
                    { 86, true, "incidunt ut saepe autem" },
                    { 87, true, "laudantium quae eligendi consequatur quia et vero autem" },
                    { 88, false, "vitae aut excepturi laboriosam sint aliquam et et accusantium" },
                    { 89, true, "sequi ut omnis et" },
                    { 90, true, "molestiae nisi accusantium tenetur dolorem et" },
                    { 91, true, "nulla quis consequatur saepe qui id expedita" },
                    { 92, true, "in omnis laboriosam" },
                    { 93, true, "odio iure consequatur molestiae quibusdam necessitatibus quia sint" },
                    { 94, false, "facilis modi saepe mollitia" },
                    { 95, true, "vel nihil et molestiae iusto assumenda nemo quo ut" },
                    { 96, false, "nobis suscipit ducimus enim asperiores voluptas" },
                    { 97, false, "dolorum laboriosam eos qui iure aliquam" },
                    { 98, true, "debitis accusantium ut quo facilis nihil quis sapiente necessitatibus" },
                    { 77, false, "maiores aut nesciunt delectus exercitationem vel assumenda eligendi at" },
                    { 76, true, "sequi dolorem sed" },
                    { 75, false, "occaecati adipisci est possimus totam" },
                    { 74, false, "expedita tempore nobis eveniet laborum maiores" },
                    { 52, false, "nesciunt dolorum quis recusandae ad pariatur ratione" },
                    { 53, false, "qui labore est occaecati recusandae aliquid quam" },
                    { 54, true, "quis et est ut voluptate quam dolor" },
                    { 55, true, "voluptatum omnis minima qui occaecati provident nulla voluptatem ratione" },
                    { 56, true, "deleniti ea temporibus enim" },
                    { 57, false, "pariatur et magnam ea doloribus similique voluptatem rerum quia" },
                    { 58, false, "est dicta totam qui explicabo doloribus qui dignissimos" },
                    { 59, false, "perspiciatis velit id laborum placeat iusto et aliquam odio" },
                    { 60, true, "et sequi qui architecto ut adipisci" },
                    { 61, true, "odit optio omnis qui sunt" },
                    { 199, true, "numquam repellendus a magnam" },
                    { 62, false, "et placeat et tempore aspernatur sint numquam" },
                    { 64, false, "voluptas consequatur qui ut quia magnam nemo esse" },
                    { 65, false, "fugiat pariatur ratione ut asperiores necessitatibus magni" },
                    { 66, false, "rerum eum molestias autem voluptatum sit optio" },
                    { 67, false, "quia voluptatibus voluptatem quos similique maiores repellat" },
                    { 68, false, "aut id perspiciatis voluptatem iusto" },
                    { 69, false, "doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit" },
                    { 70, false, "ut sequi accusantium et mollitia delectus sunt" },
                    { 71, false, "aut velit saepe ullam" },
                    { 72, false, "praesentium facilis facere quis harum voluptatibus voluptatem eum" },
                    { 73, true, "sint amet quia totam corporis qui exercitationem commodi" },
                    { 63, true, "doloremque aut dolores quidem fuga qui nulla" },
                    { 200, false, "ipsam aperiam voluptates qui" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Todos");
        }
    }
}
